#ifndef CUSTOM_H
#define CUSTOM_H

#define COLOR_BG 0xff162447

#define COLOR_STATUS_BAR 0xff1b1b2f
#define COLOR_STATUS_NORMAL 0xffa8df65
#define COLOR_STATUS_INSERT 0xffe43f5a

#define COLOR_PANEL_SELECTED 0xffdddddd
#define COLOR_PANEL_LAST_SELECTED 0xff888888

#endif //CUSTOM_H
